// This file is auto-generated by @hey-api/openapi-ts

export type Body_upload_api_v1_receipts_upload__post = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Receipt = {
    items: Array<ReceiptItem>;
};

export type ReceiptItem = {
    name: string;
    price: number;
    quantity: number;
    total: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthApiV1HealthGetResponse = (unknown);

export type HealthApiV1HealthGetError = unknown;

export type UploadApiV1ReceiptsUploadPostData = {
    body: Body_upload_api_v1_receipts_upload__post;
};

export type UploadApiV1ReceiptsUploadPostResponse = (Receipt);

export type UploadApiV1ReceiptsUploadPostError = (HTTPValidationError);

export type GetReceiptApiV1ReceiptsGetResponse = (Receipt);

export type GetReceiptApiV1ReceiptsGetError = unknown;