// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-fetch';
import type { HealthApiV1HealthGetError, HealthApiV1HealthGetResponse, UploadApiV1ReceiptsUploadPostData, UploadApiV1ReceiptsUploadPostError, UploadApiV1ReceiptsUploadPostResponse, GetReceiptApiV1ReceiptsGetError, GetReceiptApiV1ReceiptsGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Health
 */
export const healthApiV1HealthGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<HealthApiV1HealthGetResponse, HealthApiV1HealthGetError, ThrowOnError>({
    ...options,
    url: '/api/v1/health/'
}); };

/**
 * Upload
 */
export const uploadApiV1ReceiptsUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadApiV1ReceiptsUploadPostData, ThrowOnError>) => { return (options?.client ?? client).post<UploadApiV1ReceiptsUploadPostResponse, UploadApiV1ReceiptsUploadPostError, ThrowOnError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
        'Content-Type': null
    },
    url: '/api/v1/receipts/upload/'
}); };

/**
 * Get Receipt
 */
export const getReceiptApiV1ReceiptsGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetReceiptApiV1ReceiptsGetResponse, GetReceiptApiV1ReceiptsGetError, ThrowOnError>({
    ...options,
    url: '/api/v1/receipts/'
}); };