// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-fetch';
import type { GetReceiptApiBillsGetError, GetReceiptApiBillsGetResponse, CreateUploadFileApiBillsPostData, CreateUploadFileApiBillsPostError, CreateUploadFileApiBillsPostResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Receipt
 */
export const getReceiptApiBillsGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetReceiptApiBillsGetResponse, GetReceiptApiBillsGetError, ThrowOnError>({
    ...options,
    url: '/api/bills/'
}); };

/**
 * Create Upload File
 */
export const createUploadFileApiBillsPost = <ThrowOnError extends boolean = false>(options: Options<CreateUploadFileApiBillsPostData, ThrowOnError>) => { return (options?.client ?? client).post<CreateUploadFileApiBillsPostResponse, CreateUploadFileApiBillsPostError, ThrowOnError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
        'Content-Type': null
    },
    url: '/api/bills/'
}); };